services: 
  postgres:
    image: postgres:15
    container_name: pokemon-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    env_file:
      - ../src/.env

volumes:
  postgres_data:
